"""
Prep phase — WITH internet access.
Strategy: solve ALL tasks NOW using 5 cheap OpenRouter models + validation agent.
Cache answers → inference phase just reads the cache (no internet needed).
"""

import json
import os
import sys
import asyncio
import httpx
from pathlib import Path
from typing import List, Dict, Optional, Any
from copy import deepcopy

# ── Config ───────────────────────────────────────────────────────────────────

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY", "")
OR_BASE = "https://openrouter.ai/api/v1/chat/completions"
INPUT_DIR  = Path(os.getenv("INPUT_DIR",  "/input"))
OUTPUT_DIR = Path(os.getenv("OUTPUT_DIR", "/output"))
CACHE_FILE = Path("/app/cache.json")

# Persistent cross-eval cache (committed in our GitHub repo).
# Validator clones repo fresh each eval — historical_cache.json comes with code.
# Contains {task_hash: predicted_grid} from previous successful preps.
# Carry-over tasks (80/100 daily) return repeatedly → cache hits compound.
HISTORICAL_CACHE_FILE = Path(__file__).parent / "historical_cache.json"

# 5 fast models good at code — all respond in < 30s (no reasoning/thinking models)
# :nitro suffix routes to fastest provider (2-3× speedup, small cost premium)
SOLVER_MODELS = [
    "qwen/qwen3-coder-30b-a3b-instruct:nitro",
    "deepseek/deepseek-v4-flash",                 # single provider, :nitro no-op
    "google/gemini-2.5-flash:nitro",              # upgraded 2.0 → 2.5
    "openai/gpt-4o-mini:nitro",
    "xiaomi/mimo-v2-flash:nitro",
]



# ── Helpers ──────────────────────────────────────────────────────────────────

def grid_str(grid: List[List[int]]) -> str:
    return "\n".join(" ".join(str(c) for c in row) for row in grid)

def grids_match(a, b) -> bool:
    if len(a) != len(b): return False
    return all(len(a[i]) == len(b[i]) and a[i] == b[i] for i in range(len(a)))

def parse_grid(text: str) -> Optional[List[List[int]]]:
    """Extract JSON grid from LLM response."""
    text = text.strip()
    # Try JSON directly
    for start in ['[[', '[']:
        idx = text.find(start)
        if idx != -1:
            # Find matching close
            depth, end = 0, -1
            for i, c in enumerate(text[idx:], idx):
                if c == '[': depth += 1
                elif c == ']':
                    depth -= 1
                    if depth == 0:
                        end = i + 1
                        break
            if end != -1:
                try:
                    grid = json.loads(text[idx:end])
                    if isinstance(grid, list) and grid and isinstance(grid[0], list):
                        # Validate: all ints 0-9, rectangular, ≤30x30
                        if len(grid) <= 30 and len(grid[0]) <= 30:
                            if all(isinstance(v, int) and 0 <= v <= 9
                                   for row in grid for v in row):
                                return grid
                except Exception:
                    pass
    return None


async def call_model(client: httpx.AsyncClient, model: str,
                     messages: List[Dict], temperature: float = 0.2,
                     max_tokens: int = 4000) -> str:
    """
    Env vars (production-tunable):
      CALL_TIMEOUT_SEC (default 30): per-call timeout
      CALL_RETRIES (default 1): max retries on transient errors
    Bench can set generous values via env; prod uses defaults.
    """
    timeout = float(os.getenv("CALL_TIMEOUT_SEC", "30"))
    max_retries = int(os.getenv("CALL_RETRIES", "1"))
    for attempt in range(max_retries + 1):
        try:
            r = await client.post(OR_BASE, headers={
                "Authorization": f"Bearer {OPENROUTER_API_KEY}",
                "Content-Type": "application/json",
            }, json={
                "model": model,
                "messages": messages,
                "max_tokens": max_tokens,
                "temperature": temperature,
            }, timeout=timeout)
            data = r.json()
            if "choices" in data and data["choices"]:
                return data["choices"][0]["message"].get("content") or ""
            if attempt < max_retries:
                await asyncio.sleep(1)
        except Exception:
            if attempt < max_retries:
                await asyncio.sleep(1)
    return ""


# ── Program Synthesis Prompts ─────────────────────────────────────────────────

SYSTEM_SYNTHESIS = """You are an expert at ARC-AGI-2 visual reasoning puzzles.

ARC puzzles show a transformation rule via 3 input/output pairs. Your job:
identify the rule and write Python code that applies it to any input grid.

## Task structure (important for ARC-AGI-2 specifically)

Each puzzle is generated by composing TWO things:
  1. A "base operation" (object detection, pattern completion, filling, etc.)
  2. A chain of 3-7 geometric/color transformations applied on top

So the transformation you see is actually `chain(base_fn(input))`.
You don't need to decompose them — just learn the full input→output mapping.

## Common ARC operations

Spatial transforms: rotate 90/180/270, flip h/v/diag/antidiag, transpose,
                    zoom 2x/3x, downsample 2x, shift by N cells.
Color ops:          swap, remove, highlight, palette permutation.
Gravity:            non-zero cells fall to one edge.
Object ops:         connected components, copy/move/recolor objects,
                    pattern completion, fill enclosed regions.

## How to write the function

```python
def transform(grid: list[list[int]]) -> list[list[int]]:
    from copy import deepcopy
    result = deepcopy(grid)
    # ... transformation logic here ...
    return result
```

Rules:
- Standard library ONLY (copy, itertools, math, collections, functools, re)
- Output must be 2D list of integers 0-9, max 30x30
- The same logic must work for all examples — DO NOT hardcode example outputs
- Verify in your head that your function produces the correct output for all 3 examples

Start your response with brief reasoning in <reasoning></reasoning> tags identifying
the transformation. Then output the function in a ```python``` block."""


def make_synthesis_prompt(train: List[Dict]) -> str:
    """V2: includes worked example demonstrating general (non-hardcoded) logic."""
    lines = []
    # Worked example shows the kind of general logic that works
    lines.append("Here is a worked example of the kind of reasoning that works well:\n")
    lines.append("EXAMPLE TASK:")
    lines.append("  Input:  [[0,0,1],[0,1,0],[1,0,0]]")
    lines.append("  Output: [[0,0,1,0,0,1],[0,1,0,0,1,0],[1,0,0,1,0,0],"
                 "[0,0,1,0,0,1],[0,1,0,0,1,0],[1,0,0,1,0,0]]")
    lines.append("")
    lines.append("GOOD REASONING:")
    lines.append("  <reasoning>The output is the input tiled 2x2: rows repeat vertically and")
    lines.append("  columns horizontally. Output dimensions = 2*H × 2*W,")
    lines.append("  and output[r][c] = input[r % H][c % W].</reasoning>")
    lines.append("")
    lines.append("GOOD CODE (general logic, NOT hardcoded outputs):")
    lines.append("  ```python")
    lines.append("  def transform(grid):")
    lines.append("      H, W = len(grid), len(grid[0])")
    lines.append("      return [[grid[r % H][c % W] for c in range(2*W)] for r in range(2*H)]")
    lines.append("  ```")
    lines.append("")
    lines.append("Now solve the ACTUAL task below using the same approach.")
    lines.append("")
    lines.append("ACTUAL TASK:")
    for i, ex in enumerate(train[:3]):
        lines.append(f"\nExample {i+1}:")
        lines.append(f"  Input:  {json.dumps(ex['input'])}")
        lines.append(f"  Output: {json.dumps(ex['output'])}")
    lines.append(
        "\nWrite `transform(grid)` that produces the correct output for ALL examples above.\n"
        "Standard library only. Return ONLY the function inside ```python``` block."
    )
    return "\n".join(lines)


# ── Code execution helpers ────────────────────────────────────────────────────

def extract_code(text: str) -> str:
    if not text:
        return ""
    if "```python" in text:
        return text.split("```python")[1].split("```")[0].strip()
    if "```" in text:
        return text.split("```")[1].split("```")[0].strip()
    if "def transform" in text:
        lines = text.split("\n")
        start = next((i for i, l in enumerate(lines) if "def transform" in l), None)
        if start is not None:
            return "\n".join(lines[start:])
    return ""


def _run_with_timeout(fn: Any, grid: List[List[int]], timeout_sec: int = 5) -> Optional[List[List[int]]]:
    """
    Run fn(grid) with protection against slow/infinite code.
    Uses threading.Timer to set a stop flag + recursion limit in the fn namespace.
    SIGALRM is NOT used — it breaks the asyncio event loop on macOS/Linux.
    """
    import threading
    import sys

    stopped = threading.Event()
    result_holder: list = []

    def _target():
        old_limit = sys.getrecursionlimit()
        sys.setrecursionlimit(300)
        try:
            result_holder.append(fn(grid))
        except Exception:
            pass
        finally:
            sys.setrecursionlimit(old_limit)

    t = threading.Thread(target=_target, daemon=True)
    t.start()
    t.join(timeout=timeout_sec)

    if t.is_alive() or not result_holder:
        return None
    return result_holder[0]


def compile_and_validate(code: str, train: List[Dict]) -> Optional[Any]:
    """Compile code, run on all training pairs. Return fn if ALL pass, else None."""
    if not code:
        return None
    try:
        ns: Dict = {}
        exec(
            "from typing import List, Dict, Optional, Tuple, Set\n"
            "from copy import deepcopy\n"
            "import itertools, math, collections, functools, re\n"
            "from collections import Counter, defaultdict, deque\n",
            ns,
        )
        exec(code, ns)
        fn = ns.get("transform")
        if not callable(fn):
            return None

        for ex in train:
            # deepcopy prevents generated code from mutating training data in-place
            # timeout prevents infinite loops from hanging the process
            pred = _run_with_timeout(fn, deepcopy(ex["input"]), timeout_sec=5)
            if not pred or not pred[0]:
                return None
            if pred != ex["output"]:
                return None

        return fn
    except Exception:
        return None


def apply_safe(fn: Any, grid: List[List[int]]) -> Optional[List[List[int]]]:
    try:
        r = fn(grid)
        if r and r[0] and len(r) <= 30 and len(r[0]) <= 30:
            if all(isinstance(v, int) and 0 <= v <= 9 for row in r for v in row):
                return r
    except Exception:
        pass
    return None


def vote_outputs(outputs: List[List[List[int]]]) -> List[List[int]]:
    counts: Dict[str, int] = {}
    for g in outputs:
        k = json.dumps(g)
        counts[k] = counts.get(k, 0) + 1
    return json.loads(max(counts, key=counts.__getitem__))


def evaluate_program(code: str, train: List[Dict]) -> Dict:
    """
    Compile code and run on all training pairs.
    Returns {"fn": callable|None, "pass_count": int,
             "failing": [(example, pred|None), ...]}
    Unlike compile_and_validate, does not fail-fast — collects partial results.
    """
    empty = {"fn": None, "pass_count": 0, "failing": []}
    if not code:
        return empty
    try:
        ns: Dict = {}
        exec(
            "from typing import List, Dict, Optional, Tuple, Set\n"
            "from copy import deepcopy\n"
            "import itertools, math, collections, functools, re\n"
            "from collections import Counter, defaultdict, deque\n",
            ns,
        )
        exec(code, ns)
        fn = ns.get("transform")
        if not callable(fn):
            return empty
    except Exception:
        return empty

    pass_count = 0
    failing: List[tuple] = []
    for ex in train:
        raw = _run_with_timeout(fn, deepcopy(ex["input"]), timeout_sec=5)
        # Normalise: None if invalid/timeout, else the grid
        pred: Optional[List[List[int]]] = None
        if raw and raw[0] and len(raw) <= 30 and len(raw[0]) <= 30:
            if all(isinstance(v, int) and 0 <= v <= 9 for row in raw for v in row):
                pred = raw
        if pred is not None and pred == ex["output"]:
            pass_count += 1
        else:
            failing.append((ex, pred))  # (example_dict, what_we_got)

    return {"fn": fn, "pass_count": pass_count, "failing": failing}


# ── Repair loop ───────────────────────────────────────────────────────────────

REPAIR_MODEL = "deepseek/deepseek-v4-flash"  # fast, strong at code debugging

SYSTEM_REPAIR = """You are debugging a Python ARC-AGI-2 solver function.
It passes 2 out of 3 training examples but fails on one specific case.
Fix ONLY the bug causing that failure — preserve all logic that works.
Return ONLY the corrected function inside ```python ... ``` block."""


def make_repair_prompt(code: str, fail_ex: Dict,
                       fail_pred: Optional[List[List[int]]]) -> str:
    got = json.dumps(fail_pred) if fail_pred is not None else "ERROR (exception)"
    return (
        f"This function passes 2/3 training examples but fails on one:\n\n"
        f"```python\n{code}\n```\n\n"
        f"FAILING EXAMPLE:\n"
        f"Input:    {json.dumps(fail_ex['input'])}\n"
        f"Expected: {json.dumps(fail_ex['output'])}\n"
        f"Got:      {got}\n\n"
        f"Fix the bug. Do not change logic that works for passing examples.\n"
        f"Return ONLY the corrected function inside ```python ... ``` block."
    )


async def repair_program(
    client: httpx.AsyncClient,
    code: str,
    fail_ex: Dict,
    fail_pred: Optional[List[List[int]]],
    train: List[Dict],
    test_input: List[List[int]],
) -> Optional[List[List[int]]]:
    """
    Attempt to repair a 2/3-passing program.
    Makes up to 2 sequential calls at T=0.1.
    Returns test output if repair passes ALL train pairs, else None.
    """
    repair_prompt = make_repair_prompt(code, fail_ex, fail_pred)
    messages = [
        {"role": "system", "content": SYSTEM_REPAIR},
        {"role": "user",   "content": repair_prompt},
    ]
    # Attempt 1: T=0.1 (focused fix). Attempt 2: T=0.4 (if same prompt → same answer at T=0.1)
    for attempt, temperature in enumerate([0.1, 0.4]):
        resp = await call_model(client, REPAIR_MODEL, messages, temperature=temperature)
        new_code = extract_code(resp)
        fn = compile_and_validate(new_code, train)   # strict: ALL pairs must pass
        if fn is not None:
            result = apply_safe(fn, deepcopy(test_input))
            if result:
                return result
    return None


# ── Fallback: direct grid prediction (legacy) ─────────────────────────────────

SYSTEM_DIRECT = """You are an expert at ARC-AGI-2 visual reasoning puzzles.
Output ONLY the answer grid as JSON array of arrays, like: [[1,2],[3,4]]
No explanation. No markdown. Just the JSON array."""

def make_direct_prompt(train: List[Dict], test_input: List[List[int]]) -> str:
    lines = ["Find the pattern and predict the test output:\n"]
    for i, ex in enumerate(train[:3]):
        lines.append(f"Train {i+1} input:  {json.dumps(ex['input'])}")
        lines.append(f"Train {i+1} output: {json.dumps(ex['output'])}\n")
    lines.append(f"Test input: {json.dumps(test_input)}")
    lines.append("\nOutput ONLY the result grid as JSON array of arrays.")
    return "\n".join(lines)


# ── Core: Solve One Task ──────────────────────────────────────────────────────

async def solve_task(client: httpx.AsyncClient, task: Dict) -> Optional[List[List[int]]]:
    """
    Production speed knobs (env vars):
      PREP_TASK_TIMEOUT (default 45)  — hard cap per task in seconds
      SKIP_2ND_TEMP     (default 0)   — only T=0.3 round, skip T=0.7
      SKIP_REPAIR       (default 0)   — skip repair loop entirely
      SKIP_DIRECT_FALLBACK (default 0) — skip Phase 2 direct prediction
      PROD_MAX_TOKENS   (default 2500) — max tokens per LLM response
    Bench tunable: CALL_TIMEOUT_SEC, CALL_RETRIES.
    """
    per_task_timeout = float(os.getenv("PREP_TASK_TIMEOUT", "300"))
    try:
        return await asyncio.wait_for(
            _inner_solve_task(client, task), timeout=per_task_timeout
        )
    except asyncio.TimeoutError:
        print(f"  [{task.get('task_hash', '?')[:8]}] ⏰ per-task timeout ({per_task_timeout}s)")
        return None


async def _inner_solve_task(client: httpx.AsyncClient, task: Dict) -> Optional[List[List[int]]]:
    train      = task["train_examples"]
    test_input = task["test_input"]
    task_hash  = task.get("task_hash", "?")

    skip_2nd_temp = os.getenv("SKIP_2ND_TEMP", "0") == "1"
    skip_repair = os.getenv("SKIP_REPAIR", "0") == "1"
    skip_direct = os.getenv("SKIP_DIRECT_FALLBACK", "0") == "1"
    prod_max_tokens = int(os.getenv("PROD_MAX_TOKENS", "2500"))

    # ── Phase 0: Chain inversion attempt (no LLM cost) ────────────────────────
    # If output = chain(base_fn(input)) with base_fn = identity, we can solve
    # the task purely symbolically by applying the discovered forward chain.
    # Fast (~1s), zero LLM cost. Either it works perfectly or skipped.
    if os.getenv("ENABLE_CHAIN_INVERSION", "1") == "1":
        try:
            from arc_chain_inverter import (
                find_inverse_chain, forward_chain_from_inverse, apply_forward_chain
            )
            inv_chain = find_inverse_chain(train, max_depth=4,
                                           require_identity_match=True)
            if inv_chain:
                forward_fns = forward_chain_from_inverse(inv_chain)
                predicted = apply_forward_chain(test_input, forward_fns)
                if predicted:
                    print(f"  [{task_hash[:8]}] ⚡ Chain inversion: {inv_chain} (no LLM!)")
                    return predicted
        except Exception as e:
            print(f"  [{task_hash[:8]}] chain inversion error: {e}")

    synthesis_prompt = make_synthesis_prompt(train)

    # ── Phase 1: Program synthesis — T=0.3 (+ T=0.7 unless SKIP_2ND_TEMP=1) ─────
    passing_outputs: List[List[List[int]]] = []
    repair_candidates: List[tuple] = []  # (code, fail_ex, fail_pred)

    temperatures = (0.3,) if skip_2nd_temp else (0.3, 0.7)
    for temperature in temperatures:
        synth_tasks = [
            call_model(client, model, [
                {"role": "system", "content": SYSTEM_SYNTHESIS},
                {"role": "user",   "content": synthesis_prompt},
            ], temperature=temperature, max_tokens=prod_max_tokens)
            for model in SOLVER_MODELS
        ]
        responses = await asyncio.gather(*synth_tasks)

        for resp in responses:
            code = extract_code(resp)
            if not code:
                continue
            info = evaluate_program(code, train)
            if info["pass_count"] == len(train):
                result = apply_safe(info["fn"], deepcopy(test_input))
                if result:
                    passing_outputs.append(result)
            elif not skip_repair and info["pass_count"] >= 2 and info["failing"]:
                fail_ex, fail_pred = info["failing"][0]
                repair_candidates.append((code, fail_ex, fail_pred))

        if passing_outputs:
            break  # найден рабочий код — не тратим T=0.7

    # ── Phase 1.25: LOO (leave-one-out) generalization filter ────────────────
    # DEFAULT DISABLED (bench Phase 3 showed LOO rejected b001 — our only
    # consistent winner — because LOO synthesis from 2 pairs failed not because
    # of overfit but because LLM needs 3 examples to disambiguate the rule.
    # False-positive rate too high to use as strict filter.)
    # To re-enable: ENABLE_LOO=1
    if passing_outputs and os.getenv("ENABLE_LOO", "0") == "1":
        loo_passed = await loo_verify(client, train)
        if not loo_passed:
            print(f"  [{task_hash[:8]}] ⚠️ LOO filter rejected {len(passing_outputs)} candidates (overfit)")
            passing_outputs = []

    if passing_outputs:
        result = vote_outputs(passing_outputs)
        print(f"  [{task_hash[:8]}] ✅ Synthesis: {len(passing_outputs)} passed → voted")
        return result

    # ── Phase 1.5: Repair loop — fix 2/3 candidates ──────────────────────────
    if repair_candidates and not skip_repair:
        # Deduplicate by full code string, keep order (first = earliest found)
        seen: set = set()
        unique: List[tuple] = []
        for code, fail_ex, fail_pred in repair_candidates:
            if code not in seen:
                seen.add(code)
                unique.append((code, fail_ex, fail_pred))

        # Run up to 3 candidates in parallel (each makes ≤2 sequential repair calls)
        repair_tasks = [
            repair_program(client, code, fail_ex, fail_pred, train, test_input)
            for code, fail_ex, fail_pred in unique[:3]
        ]
        repaired = await asyncio.gather(*repair_tasks)

        for r in repaired:
            if r is not None:
                passing_outputs.append(r)

        if passing_outputs:
            result = vote_outputs(passing_outputs)
            n_fixed = sum(1 for r in repaired if r is not None)
            print(f"  [{task_hash[:8]}] 🔧 Repair: {n_fixed}/{len(unique[:3])} fixed → voted")
            return result
        else:
            print(f"  [{task_hash[:8]}] 🔧 Repair: 0/{len(unique[:3])} succeeded")

    # ── Phase 2: Fallback — direct grid prediction (SKIP_DIRECT_FALLBACK to disable) ──
    # Empirically gives 0 correct results on bench A — pure waste in prod.
    if skip_direct:
        print(f"  [{task_hash[:8]}] ❌ Synthesis failed (direct fallback skipped)")
        return None

    direct_prompt = make_direct_prompt(train, test_input)
    direct_tasks = [
        call_model(client, model, [
            {"role": "system", "content": SYSTEM_DIRECT},
            {"role": "user",   "content": direct_prompt},
        ], temperature=0.1)
        for model in SOLVER_MODELS
    ]
    direct_responses = await asyncio.gather(*direct_tasks)

    candidates = [g for resp in direct_responses if (g := parse_grid(resp))]
    if not candidates:
        print(f"  [{task_hash[:8]}] ❌ Both phases failed")
        return None

    result = vote_outputs(candidates)
    print(f"  [{task_hash[:8]}] ⚠️ Direct fallback: {len(candidates)}/5 grids parsed")
    return result


# ── LOO (Leave-One-Out) generalization filter ────────────────────────────────

LOO_MODEL = os.getenv("LOO_MODEL", "deepseek/deepseek-v4-flash")


async def loo_verify(client: httpx.AsyncClient, train: List[Dict]) -> bool:
    """
    Leave-one-out generalization check.

    For each of 3 train pairs:
      Synthesize a program SHOWING ONLY the other 2 pairs.
      Verify it correctly predicts the held-out 3rd pair.

    If ALL 3 LOO syntheses succeed → the rule is learnable from less data
    (high confidence the candidate programs generalize, not overfit).

    If ANY fails → likely the candidates are overfit to this specific train set.

    Costs 3 parallel LLM calls (one extra time-equivalent vs 1 call).
    Worthwhile only if it filters out wrong answers (verify via bench).
    """
    if len(train) != 3:
        return True   # can't do LOO without 3 train pairs

    async def _one_loo(hold_idx: int) -> bool:
        loo_train = [train[i] for i in range(3) if i != hold_idx]
        held_out = train[hold_idx]
        msgs = [
            {"role": "system", "content": SYSTEM_SYNTHESIS},
            {"role": "user",   "content": make_synthesis_prompt(loo_train)},
        ]
        try:
            response = await call_model(client, LOO_MODEL, msgs, temperature=0.3)
            loo_code = extract_code(response)
            if not loo_code:
                return False
            # Validate generated code on the held-out pair only.
            # compile_and_validate runs the code on each pair, returns fn iff all pass.
            loo_fn = compile_and_validate(loo_code, [held_out])
            return loo_fn is not None
        except Exception:
            return False

    results = await asyncio.gather(
        *[_one_loo(i) for i in range(3)],
        return_exceptions=True,
    )
    return all(r is True for r in results)


# ── Historical cache (cross-eval persistent via GitHub) ──────────────────────

def _load_historical_cache() -> Dict:
    """
    Load historical cache from repo (committed JSON file).
    Schema: {task_hash: predicted_grid}
    Empty dict if file missing or unreadable.
    """
    if not HISTORICAL_CACHE_FILE.exists():
        return {}
    try:
        data = json.loads(HISTORICAL_CACHE_FILE.read_text())
        # Sanity: must be dict, values must be 2D grids of ints 0-9
        if not isinstance(data, dict):
            return {}
        clean = {}
        for k, v in data.items():
            if not isinstance(k, str):
                continue
            if not isinstance(v, list) or not v or not isinstance(v[0], list):
                continue
            if len(v) > 30 or len(v[0]) > 30:
                continue
            if not all(isinstance(x, int) and 0 <= x <= 9 for row in v for x in row):
                continue
            clean[k] = v
        return clean
    except Exception as e:
        print(f"⚠️ Historical cache load failed: {e}")
        return {}


def _update_historical_cache(old: Dict, fresh: Dict) -> None:
    """
    Merge fresh successful solutions into historical cache and write back.
    Only adds non-None solutions; preserves existing entries.
    """
    merged = dict(old)  # copy historical
    added = 0
    for task_hash, grid in fresh.items():
        if grid is None:
            continue
        if task_hash not in merged:
            merged[task_hash] = grid
            added += 1
    if added == 0:
        print("  No new entries for historical cache")
        return
    try:
        HISTORICAL_CACHE_FILE.write_text(json.dumps(merged, indent=2, sort_keys=True))
        print(f"  Historical cache updated: +{added} entries (total {len(merged)})")
    except Exception as e:
        print(f"⚠️ Historical cache save failed: {e}")


# ── Main Prep Flow ────────────────────────────────────────────────────────────

async def run_prep():
    print("=" * 60)
    print("PREP PHASE: Solving tasks with OpenRouter ensemble")
    print("=" * 60)

    # Load input data
    input_file = INPUT_DIR / "miner_current_dataset.json"
    if not input_file.exists():
        print(f"Input file not found: {input_file}. Downloading vLLM model instead.")
        await download_fallback_model()
        return

    data = json.loads(input_file.read_text())
    tasks = data.get("tasks", [])
    print(f"Found {len(tasks)} tasks to solve")

    # ── Load historical cache (from previous evals via GitHub) ─────────────
    historical_cache = _load_historical_cache()
    hist_hits = sum(1 for t in tasks if t.get("task_hash") in historical_cache)
    print(f"Historical cache: {len(historical_cache)} entries, "
          f"{hist_hits}/{len(tasks)} of today's tasks already known")

    # Filter out tasks we already have answers for (save time + API cost)
    tasks_to_solve = [t for t in tasks if t.get("task_hash") not in historical_cache]
    print(f"Tasks to solve fresh: {len(tasks_to_solve)} (skipping {hist_hits} cached)")

    if not OPENROUTER_API_KEY:
        print("WARNING: No OPENROUTER_API_KEY — falling back to vLLM only")
        await download_fallback_model()
        return

    # ── PARALLELIZED PREP (3 phases concurrent where possible) ────────────────
    # OpenRouter solving: network I/O on external API (independent of GPU/HF)
    # Model download:     network I/O on HuggingFace CDN
    # TTT training:       GPU compute (must wait for model download first)
    # Sequential was 65-90 min — parallel ~40 min. Critical for prep_timeout.

    BATCH_SIZE = int(os.getenv("BATCH_SIZE", "4"))

    async def _run_openrouter_ensemble() -> Dict:
        """Solve uncached tasks via OpenRouter. Returns cache dict."""
        cache_local: Dict = {}
        if not tasks_to_solve:
            print("\n(All tasks already in historical cache, skipping OpenRouter)")
            return cache_local
        async with httpx.AsyncClient(timeout=90.0) as client:
            for batch_start in range(0, len(tasks_to_solve), BATCH_SIZE):
                batch = tasks_to_solve[batch_start:batch_start + BATCH_SIZE]
                end = min(batch_start + BATCH_SIZE, len(tasks_to_solve))
                print(f"\n[OR {batch_start+1}-{end}/{len(tasks_to_solve)}] batch...")
                results = await asyncio.gather(
                    *[solve_task(client, t) for t in batch],
                    return_exceptions=True,
                )
                for task, result in zip(batch, results):
                    h = task["task_hash"]
                    cache_local[h] = None if isinstance(result, Exception) else result
        return cache_local

    async def _run_ttt_after_download():
        """Wait for model, then run TTT in a thread (GPU-bound, sync)."""
        if os.getenv("ENABLE_TTT", "1") != "1":
            print("\n(TTT disabled via ENABLE_TTT=0)")
            return False
        # Download must finish before TTT (TTT loads base model from disk)
        await download_fallback_model()
        try:
            print("\n" + "=" * 60)
            print("TTT - Test-Time Training (NVARC recipe)")
            print("=" * 60)
            from arc_ttt import run_ttt
            return await asyncio.to_thread(run_ttt, input_file)
        except Exception as e:
            print(f"⚠️ TTT exception: {e}")
            import traceback
            traceback.print_exc()
            return False

    print("\n🚀 Starting parallel: OpenRouter ensemble + (model download → TTT)")
    openrouter_task = asyncio.create_task(_run_openrouter_ensemble())
    ttt_task = asyncio.create_task(_run_ttt_after_download())

    # Wait for both; return_exceptions so one failure doesn't kill the other
    cache_result, ttt_result = await asyncio.gather(
        openrouter_task, ttt_task, return_exceptions=True,
    )

    # Handle OpenRouter outcome
    if isinstance(cache_result, Exception):
        print(f"⚠️ OpenRouter ensemble failed: {cache_result}")
        cache = {}
    else:
        cache = cache_result

    # Handle TTT outcome
    if isinstance(ttt_result, Exception):
        print(f"⚠️ TTT phase exception: {ttt_result}")
    elif ttt_result:
        print("✅ TTT merged model ready — vLLM will serve it in inference")
    else:
        print("⚠️ TTT failed — fallback base model in mistral-ttt-merged path")

    # Merge: historical (known answers for this eval's tasks) + fresh cache
    merged_cache: Dict = {}
    for t in tasks:
        h = t.get("task_hash")
        if h in historical_cache:
            merged_cache[h] = historical_cache[h]  # priority: known answer
        elif h in cache:
            merged_cache[h] = cache[h]              # fresh from OpenRouter

    # Save inference cache
    CACHE_FILE.parent.mkdir(parents=True, exist_ok=True)
    CACHE_FILE.write_text(json.dumps(merged_cache, indent=2))

    solved = sum(1 for v in merged_cache.values() if v is not None)
    print(f"\n✅ Cache saved: {solved}/{len(tasks)} tasks "
          f"({hist_hits} historical + {solved - hist_hits} fresh)")

    # Update historical cache: add any new successful solutions for next eval.
    # NOTE: actually pushing to GitHub happens via a separate post-prep hook
    # (e.g., GitHub Actions). Here we just write the updated file; if validator
    # mounts the repo writable, we'd commit. Otherwise file persists for the
    # current eval only and someone manually merges.
    _update_historical_cache(historical_cache, cache)


async def download_fallback_model():
    """
    Download Mistral-NeMo-Minitron-8B-ARChitects-Full-bnb-4bit for inference vLLM.

    Why this model (decided 2026-05-13 via Opus 4.7 research):
    - The 2024 ARChitects winner (53.5% on ARC-AGI-1, pre-trained on ARC tasks)
    - 4-bit bnb format: only 3.5GB on disk, ~5-7GB VRAM in vLLM
    - Custom ARC tokenizer (1 cell = 1 token) — efficient decoding
    - TTT recipe by da-fr was written specifically for this model
    - Compute: TTT fits in ~30-40 min on H200 (NVARC's 8B reference target)

    Previous choices (rejected):
    - QwQ-32B: 65GB, reasoning model with thinking tokens, ~1-2% Pass@2 without TTT
    - Soar-Qwen-14B: 28GB, TTT recipe would need adaptation, +90-200min training

    Path MUST use '--' separator: vLLM looks for /app/models/da-fr--Mistral-NeMo-...
    Reference: sandbox_runner/execution/docker_only.py line 1042.
    See: /Users/sharapov/Cloude/Project X/nvarc_implementation_plan.md
    """
    print("\nDownloading Mistral-NeMo-ARChitects-8B-4bit for vLLM...")
    try:
        from huggingface_hub import snapshot_download
        model_id = "da-fr/Mistral-NeMo-Minitron-8B-ARChitects-Full-bnb-4bit"
        save_dir = Path(os.getenv("MODEL_SAVE_DIR", "/app/models"))
        local_dir = save_dir / model_id.replace("/", "--")  # vLLM expects julien31--Soar-qwen-14b

        # Skip if already downloaded (≥10 files = complete download)
        if local_dir.exists() and len(list(local_dir.glob("*"))) >= 10:
            print(f"✅ Model already at {local_dir}, skipping download")
            return

        local_dir.mkdir(parents=True, exist_ok=True)
        path = snapshot_download(
            repo_id=model_id,
            cache_dir=str(save_dir),
            local_dir=str(local_dir),
            local_dir_use_symlinks=False,
            resume_download=True,
            ignore_patterns=["*.gguf", "*.msgpack", "*.h5", "*.ot"],
        )
        print(f"✅ Model saved to {path}")
    except Exception as e:
        print(f"⚠️ Model download failed: {e}")
        raise  # re-raise so prep phase exits with error code


def main():
    asyncio.run(run_prep())


def run_prep_phase():
    asyncio.run(run_prep())


if __name__ == "__main__":
    main()
